"""Herding versus noise: three surveillance candidates that ask whether
activity is coordinated and self reinforcing rather than merely loud.

The four candidates of version 2 read the level of volatility or the
correlation structure of order flow. A supervisor's harder question is
whether a burst of activity is a herd or noise. Three constructs from the
empirical literature answer it from different angles, and each is
implemented as a sentinel with the same interface as the others (stress
index, final flags, first alert, online flags):

  ImbalanceSentinel    the buy sell imbalance herding measure of Lakonishok,
                       Shleifer and Vishny (1992): the share of agents on the
                       majority side in excess of what independent decisions
                       would produce. A herd puts most agents on one side at
                       once; noise does not. (The return dispersion measures
                       of Christie and Huang 1995 and Chang, Cheng and
                       Khorana 2000 need a cross section of assets and are
                       therefore not implemented in this single asset market.)
  EndogeneitySentinel  the branching ratio of a self exciting Hawkes process
                       fitted to large moves, after Filimonov and Sornette
                       (2012): the share of activity generated by earlier
                       activity rather than by news. Near one the market is
                       critical; a herd raises it, exogenous noise does not.
  LeadLagSentinel      who leads and who follows: an agent whose orders
                       predict the crowd's next orders is an ignitor, and the
                       agents whose orders follow the last return are the
                       crowd. Momentum ignition (MAR Annex II) is the pattern
                       of a small leading cluster followed by a large one.

Thresholds were set on the demonstration quiet family so that each sentinel
stays within the declared false alert budget there; the conformal layer
(`conformal.py`) reports what the guarantee is worth on held out data.
"""

import numpy as np
from scipy.optimize import minimize

from ._common import _online_matrix


def _corr_cols(X, y):
    """Correlation of every column of X (T, N) with y (T,)."""
    Xc = X - X.mean(axis=0)
    yc = y - y.mean()
    denom = np.sqrt((Xc ** 2).sum(axis=0) * (yc ** 2).sum()) + 1e-12
    return (Xc * yc[:, None]).sum(axis=0) / denom


class ImbalanceSentinel:
    """Buy sell imbalance herding measure, after Lakonishok, Shleifer and
    Vishny (1992). At each step the share of active agents on the majority
    side is compared with the share expected when agents act independently;
    the excess, averaged over a rolling window, is the herding measure. A
    herd puts most agents on one side at once; noise does not. Localisation
    flags the agents that sit on the majority side most often."""
    name = "imbalance"
    label = "Buy sell imbalance (LSV herding measure)"

    def __init__(self, window=100, stride=10, h_thresh=0.16, agree_frac=0.85):
        self.window, self.stride = window, stride
        self.h_thresh, self.agree_frac = h_thresh, agree_frac

    def run(self, res):
        T, n = res.flows.shape
        stress = np.zeros(T)
        flags = np.zeros(n, dtype=bool)
        first, peak, peak_members, events = None, 0.0, None, []
        expected = np.sqrt(2.0 / (np.pi * n))          # E|2p - 1| under independence
        for t in range(0, T, self.stride):
            a = max(0, t - self.window)
            if t - a < 40:
                continue
            q = res.flows[a:t]
            sgn = np.sign(q)
            active = (sgn != 0).sum(axis=1)
            buys = (sgn > 0).sum(axis=1)
            p = np.where(active > 0, buys / np.maximum(active, 1), 0.5)
            imbalance = np.abs(2.0 * p - 1.0)
            H = float(imbalance.mean() - expected)
            score = max(0.0, H) / self.h_thresh
            stress[t:t + self.stride] = score
            if score > 1.0:
                majority = np.sign(2.0 * p - 1.0)[:, None]
                agree = (sgn == majority).mean(axis=0)
                members = np.where(agree >= self.agree_frac * agree.max())[0]
                if first is None:
                    first = t
                if score > peak:
                    peak, peak_members = score, members
                    events.append((t, members))
        if peak_members is not None:
            flags[peak_members] = True
        return {"stress_index": stress, "flags": flags, "first_alert": first,
                "flags_online": _online_matrix(T, n, events)}


def hawkes_branching_ratio(times, horizon, betas=(0.05, 0.1, 0.2, 0.4)):
    """Maximum likelihood fit of a univariate Hawkes process with an
    exponential kernel to event times in [0, horizon). The decay is profiled
    over a small grid and (mu, alpha) are optimised by L-BFGS-B with the
    branching ratio alpha/beta bounded below one. Returns (n, mu, alpha,
    beta, log likelihood); n is the branching ratio, the share of events that
    are endogenous (Filimonov and Sornette 2012)."""
    times = np.asarray(times, dtype=float)
    m = len(times)
    if m < 4:
        return 0.0, m / max(horizon, 1.0), 0.0, betas[0], 0.0
    best = None
    dts = np.diff(times)
    tail = horizon - times
    for beta in betas:
        decay = np.exp(-beta * dts)
        A = np.zeros(m)
        for i in range(1, m):
            A[i] = decay[i - 1] * (1.0 + A[i - 1])
        comp_tail = (1.0 - np.exp(-beta * tail)) / beta

        def nll(p):
            mu, alpha = p
            lam = mu + alpha * A
            if np.any(lam <= 0):
                return 1e12
            return float(-(np.log(lam).sum() - mu * horizon - alpha * comp_tail.sum()))

        x0 = np.array([0.5 * m / horizon, 0.3 * beta])
        r = minimize(nll, x0, method="L-BFGS-B",
                     bounds=[(1e-5, None), (0.0, 0.99 * beta)])
        ll = -float(r.fun)
        if best is None or ll > best[4]:
            best = (float(r.x[1] / beta), float(r.x[0]), float(r.x[1]), float(beta), ll)
    return best


class EndogeneitySentinel:
    """Branching ratio of large moves over a rolling window: the share of
    activity that is self excited. Events are steps whose absolute return
    exceeds a multiple of the window's median absolute return. Localisation
    flags agents whose absolute order flow tracks the endogenous part of the
    fitted intensity."""
    name = "endogeneity"
    label = "Endogeneity (Hawkes branching ratio)"

    def __init__(self, window=150, stride=10, event_mult=2.0, n_thresh=0.75,
                 load_frac=0.6):
        self.window, self.stride = window, stride
        self.event_mult, self.n_thresh, self.load_frac = event_mult, n_thresh, load_frac

    def run(self, res):
        T, n = res.flows.shape
        stress = np.zeros(T)
        flags = np.zeros(n, dtype=bool)
        first, peak, peak_members, events = None, 0.0, None, []
        for t in range(0, T, self.stride):
            a = max(0, t - self.window)
            if t - a < 60:
                continue
            r = res.returns[a:t]
            scale = np.median(np.abs(r[1:])) + 1e-12
            ev = np.where(np.abs(r) > self.event_mult * scale)[0].astype(float)
            br, mu, alpha, beta, _ = hawkes_branching_ratio(ev, float(t - a))
            score = br / self.n_thresh
            stress[t:t + self.stride] = score
            if score > 1.0 and len(ev) >= 4:
                # endogenous intensity at every step of the window
                steps = np.arange(t - a, dtype=float)
                lam_endo = np.zeros(len(steps))
                for e in ev:
                    mask = steps > e
                    lam_endo[mask] += alpha * np.exp(-beta * (steps[mask] - e))
                load = _corr_cols(np.abs(res.flows[a:t]), lam_endo)
                if load.max() <= 0:
                    continue
                members = np.where(load >= self.load_frac * load.max())[0]
                if first is None:
                    first = t
                if score > peak:
                    peak, peak_members = score, members
                    events.append((t, members))
        if peak_members is not None:
            flags[peak_members] = True
        return {"stress_index": stress, "flags": flags, "first_alert": first,
                "flags_online": _online_matrix(T, n, events)}


class LeadLagSentinel:
    """Lead and follow scores from lag one correlations of order flow. The
    lead score of an agent is the correlation of its flow with the crowd's
    flow one step later (excluding itself); the follow score is the
    correlation of its flow with the previous market return. The stress index
    is the standardised size of the strongest lead relative to the crowd,
    combined with the breadth of following. Flags the leaders and the
    strongest followers."""
    name = "lead_lag"
    label = "Lead lag ignition sentinel"

    def __init__(self, window=100, stride=10, z_thresh=3.0, follow_frac=0.5,
                 min_followers=8):
        self.window, self.stride, self.z_thresh = window, stride, z_thresh
        self.follow_frac, self.min_followers = follow_frac, min_followers

    def run(self, res):
        T, n = res.flows.shape
        stress = np.zeros(T)
        flags = np.zeros(n, dtype=bool)
        first, peak, peak_members, events = None, 0.0, None, []
        for t in range(0, T, self.stride):
            a = max(0, t - self.window)
            if t - a < 40:
                continue
            q = res.flows[a:t]
            r = res.returns[a:t]
            crowd_next = (q[1:].sum(axis=1)[:, None] - q[1:]) / max(1, n - 1)   # others at t+1
            lead = np.array([np.corrcoef(q[:-1, i], crowd_next[:, i])[0, 1] for i in range(n)])
            lead = np.nan_to_num(lead)
            follow = _corr_cols(q[1:], r[:-1])
            z = (lead - np.median(lead)) / (1.4826 * np.median(np.abs(lead - np.median(lead))) + 1e-9)
            breadth = float(np.mean(follow > 0.3))
            score = (z.max() / self.z_thresh) * (0.5 + breadth)
            stress[t:t + self.stride] = score
            if score > 1.0:
                leaders = np.where(z >= self.z_thresh)[0]
                followers = np.where(follow >= self.follow_frac * follow.max())[0]
                if len(followers) < self.min_followers:
                    followers = np.array([], dtype=int)
                members = np.union1d(leaders, followers)
                if len(members) == 0:
                    continue
                if first is None:
                    first = t
                if score > peak:
                    peak, peak_members = score, members
                    events.append((t, members))
        if peak_members is not None:
            flags[peak_members] = True
        return {"stress_index": stress, "flags": flags, "first_alert": first,
                "flags_online": _online_matrix(T, n, events)}


class TailDependenceSentinel:
    """Tail concordance of order flows. Linear correlation is a poor measure
    of dependence when the joint behaviour that matters sits in the tails
    (McNeil, Frey and Embrechts 2015, chapter 7: the correlation fallacies;
    tail dependence coefficients). Herding is a tail phenomenon: agents act
    together in the large moves. For each pair of agents the sentinel
    estimates the probability that both flows sit in the same tail of their
    own distributions (q under independence, one under perfect dependence),
    averages the lower and upper tails, and reads the mass of the largest
    component of agents whose tail concordance exceeds a threshold."""
    name = "tail_dependence"
    label = "Tail dependence (tail concordance)"

    def __init__(self, window=100, stride=10, q=0.15, lam_thresh=0.5, alert_level=0.125, min_comp=8):
        # lam is a tail dependence coefficient in [0, 1]: q under independence, 1 under
        # perfect dependence. lam_thresh is the edge threshold and alert_level the
        # component mass (mean lam times share of agents) that raises an alert.
        self.window, self.stride, self.q = window, stride, q
        self.lam_thresh, self.alert_level, self.min_comp = lam_thresh, alert_level, min_comp

    def run(self, res):
        T, n = res.flows.shape
        stress = np.zeros(T)
        flags = np.zeros(n, dtype=bool)
        first, peak, peak_members, events = None, 0.0, None, []
        for t in range(0, T, self.stride):
            a = max(0, t - self.window)
            if t - a < 40:
                continue
            q = res.flows[a:t]
            lo = q <= np.quantile(q, self.q, axis=0)
            hi = q >= np.quantile(q, 1 - self.q, axis=0)
            m = float(lo.shape[0])
            lam = ((lo.T.astype(float) @ lo.astype(float)) + (hi.T.astype(float) @ hi.astype(float))) / (2.0 * m * self.q)
            np.fill_diagonal(lam, 0.0)
            A = lam >= self.lam_thresh
            # largest connected component by breadth first search
            seen = np.zeros(n, dtype=bool)
            best, best_mass = None, 0.0
            for s in range(n):
                if seen[s] or not A[s].any():
                    continue
                comp, stack = [], [s]
                seen[s] = True
                while stack:
                    u = stack.pop(); comp.append(u)
                    for v in np.where(A[u] & ~seen)[0]:
                        seen[v] = True; stack.append(v)
                if len(comp) >= self.min_comp:
                    c = np.array(comp)
                    sub = lam[np.ix_(c, c)]
                    mean_lam = float(sub.sum() / max(1, len(c) ** 2 - len(c)))
                    mass = mean_lam * len(c) / n
                    if mass > best_mass:
                        best_mass, best = mass, c
            score = best_mass / self.alert_level
            stress[t:t + self.stride] = score
            if best is not None and score > 1.0:
                if first is None:
                    first = t
                if score > peak:
                    peak, peak_members = score, best
                    events.append((t, best))
        if peak_members is not None:
            flags[peak_members] = True
        return {"stress_index": stress, "flags": flags, "first_alert": first,
                "flags_online": _online_matrix(T, n, events)}


HERDING_SENTINELS = [ImbalanceSentinel, EndogeneitySentinel, LeadLagSentinel, TailDependenceSentinel]
