"""Append only, hash chained, HMAC signed rationale ledger.

Every step, tool call, gate decision and release is a record:

    seq, run_id, ts (UTC ISO), actor, event, payload, prev_hash, hash, sig

`hash` is SHA-256 over the canonical JSON of the record without `hash` and
`sig`. `prev_hash` chains records; the first record chains to a 64 zero
genesis value. `sig` is HMAC-SHA256 of `hash` under the server secret, so a
copy of the file cannot be silently regenerated by someone who does not
hold the key. The file is opened in append mode and is never truncated;
re-opening an existing ledger continues its chain.

`verify()` replays the chain and is exposed as a command line tool:

    python -m hsl.ledger verify runs/<id>/ledger.jsonl [--secret-env HSL_SECRET]
"""

import datetime
import hashlib
import hmac
import json
import os
import sys
import threading

import numpy as np

GENESIS = "0" * 64


class NumpyEncoder(json.JSONEncoder):
    """Serialise numpy scalars and arrays as plain JSON types, so the
    on disk record and the hashed record are the same object."""

    def default(self, o):
        if isinstance(o, np.bool_):
            return bool(o)
        if isinstance(o, np.integer):
            return int(o)
        if isinstance(o, np.floating):
            return float(o)
        if isinstance(o, np.ndarray):
            return o.tolist()
        if isinstance(o, (set, tuple)):
            return list(o)
        if hasattr(o, "isoformat"):
            return o.isoformat()
        return str(o)


def canonical(obj) -> bytes:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"),
                      cls=NumpyEncoder, ensure_ascii=False).encode("utf-8")


def plain(obj):
    """Round trip through the encoder so numpy types become Python types."""
    return json.loads(canonical(obj))


def sha256_hex(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def _now():
    return datetime.datetime.now(datetime.timezone.utc).isoformat(
        timespec="milliseconds")


def _sig(secret: bytes, h: str) -> str:
    return hmac.new(secret, h.encode(), hashlib.sha256).hexdigest()


class Ledger:
    """Callable: `log(event, actor=None, **payload)` appends one record."""

    def __init__(self, path, run_id, secret=None, actor="system"):
        self.path = path
        self.run_id = run_id
        self.secret = secret.encode() if isinstance(secret, str) else secret
        self.actor = actor
        self.seq = 0
        self.prev = GENESIS
        self._lock = threading.Lock()
        d = os.path.dirname(os.path.abspath(path))
        os.makedirs(d, exist_ok=True)
        if os.path.exists(path) and os.path.getsize(path) > 0:
            last = None
            with open(path, "rb") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        last = json.loads(line)
            if last:
                self.seq = int(last["seq"])
                self.prev = last["hash"]

    def __call__(self, event, actor=None, **payload):
        with self._lock:
            self.seq += 1
            rec = {"seq": self.seq, "run_id": self.run_id, "ts": _now(),
                   "actor": actor or self.actor, "event": event,
                   "payload": plain(payload), "prev_hash": self.prev}
            rec["hash"] = sha256_hex(canonical(rec))
            if self.secret:
                rec["sig"] = _sig(self.secret, rec["hash"])
            self.prev = rec["hash"]
            with open(self.path, "a", encoding="utf-8") as f:
                f.write(json.dumps(rec, cls=NumpyEncoder, ensure_ascii=False)
                        + "\n")
                f.flush()
                os.fsync(f.fileno())
            return rec

    @property
    def head(self):
        return self.prev


def verify(path, secret=None) -> dict:
    """Replay the chain. Returns a report; `ok` is True only if every
    record hashes, chains and (when a secret is given) signs correctly."""
    secret = secret.encode() if isinstance(secret, str) else secret
    errors, n, prev, seq, signed = [], 0, GENESIS, 0, 0
    run_ids = set()
    if not os.path.exists(path):
        return {"ok": False, "entries": 0, "errors": ["file not found"],
                "signed": 0, "head": None}
    with open(path, "rb") as f:
        for i, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                errors.append(f"line {i}: not JSON")
                break
            h = rec.pop("hash", None)
            sig = rec.pop("sig", None)
            if rec.get("seq") != seq + 1:
                errors.append(f"line {i}: seq {rec.get('seq')} expected {seq + 1}")
            if rec.get("prev_hash") != prev:
                errors.append(f"line {i}: chain broken (prev_hash mismatch)")
            calc = sha256_hex(canonical(rec))
            if calc != h:
                errors.append(f"line {i}: hash mismatch ({rec.get('event')})")
            if secret is not None:
                if sig is None:
                    errors.append(f"line {i}: unsigned record")
                elif not hmac.compare_digest(sig, _sig(secret, h or "")):
                    errors.append(f"line {i}: bad signature")
            if sig is not None:
                signed += 1
            run_ids.add(rec.get("run_id"))
            prev, seq, n = h, rec.get("seq", seq + 1), n + 1
            if len(errors) > 25:
                errors.append("... further errors suppressed")
                break
    if len(run_ids) > 1:
        errors.append(f"multiple run ids in one ledger: {sorted(map(str, run_ids))}")
    return {"ok": not errors, "entries": n, "signed": signed,
            "head": prev if n else None, "errors": errors,
            "run_id": next(iter(run_ids)) if len(run_ids) == 1 else None}


def read(path) -> list:
    out = []
    if not os.path.exists(path):
        return out
    with open(path, "rb") as f:
        for line in f:
            line = line.strip()
            if line:
                out.append(json.loads(line))
    return out


def _main(argv):
    import argparse
    ap = argparse.ArgumentParser(prog="python -m hsl.ledger")
    sub = ap.add_subparsers(dest="cmd", required=True)
    v = sub.add_parser("verify", help="replay and verify a ledger file")
    v.add_argument("path")
    v.add_argument("--secret-env", default="HSL_SECRET",
                   help="environment variable holding the HMAC secret "
                        "(signatures are checked only if it is set)")
    a = ap.parse_args(argv)
    if a.cmd == "verify":
        rep = verify(a.path, os.environ.get(a.secret_env) or None)
        print(json.dumps(rep, indent=2))
        return 0 if rep["ok"] else 1


if __name__ == "__main__":  # pragma: no cover
    sys.exit(_main(sys.argv[1:]))
